#!/bin/sh

SESSION=minecraft
MINECRAFT_HOME="/minecraft/server"
SERVER_JAR=$MINECRAFT_HOME/minecraft_server.jar

update_permissions() {
    chown -R minecraft:minecraft $MINECRAFT_HOME 
}

run_minecraft() {
    echo "Running Minecraft"
    echo "JVM_OPTS: $JVM_OPTS"

    PARAMS=$@
    MINECRAFT_COMMAND="java $JVM_OPTS -jar $SERVER_JAR nogui $PARAMS"

    if [ "$TERM" == "dumb" ]; then
        >&2 echo "WARNING! Dumb term detected. Switching to noconsole mode."
        >&2 echo "Safe shutdown must be done via /stop chat command."
        exec $MINECRAFT_COMMAND
    else
        tmux new -s $SESSION $MINECRAFT_COMMAND
    fi
}

console_command() {
    COMMAND=$@
    if [ "$TERM" == "dumb" ]; then
        >&2 echo "Console command not supported on a dumb term."
        exit 1
    else
        tmux send -t $SESSION $COMMAND ENTER
    fi
}

safe_shutdown() {
    echo "Performing safe shutdown..."
    console_command stop
}

case "$1" in
    run)
        shift 1
        trap safe_shutdown EXIT
        run_minecraft $@
        ;;
    permissions)
        shift 1
        update_permissions
        ;;
    console)
        shift 1
        console_command $@
        ;;
    *)
        exec "$@"
esac
