#!/bin/sh

SESSION=minecraft
MINECRAFT_HOME="/minecraft/server"
SERVER_JAR=$MINECRAFT_HOME/minecraft_server.jar

mc_start() {
    mkfifo /tmp/srv-input
    tail -f /tmp/srv-input | java $JVM_OPTS -jar $SERVER_JAR nogui $@
}

mc_exec() {
    if [ -e /tmp/srv-input ]; then
        echo "$@" > /tmp/srv-input
    else
        echo "/tmp/srv-input did not exist to write to"
    fi
}

safe_shutdown() {
    echo "Performing safe shutdown..."
    mc_exec "stop"
}

mc_kill() {

    echo "Terminating the primary container process with pid 1"
    kill 1

    sleep 3

    echo "Service could not be terminated, killing..."
    kill -SIGKILL 1
    echo "Killed"
}

mc_restart() {
   mc_exec "save-all"
}

case "$1" in
    start)
        shift 1
        trap safe_shutdown SIGHUP
        mc_start $@
        ;;
    stop) 
	shift 1
	safe_shutdown
	;;
    exec)
        shift 1
        mc_exec $@
        ;;
    *)
 	echo "Usage: $(readlink -f $0) {start|stop|exec}"
  	exit 1
esac
